### ISSUE TITLE
Fatal error: Class 'Saferpay' not found

### ISSUE THREAD

**Issue by beeInteractive** [payment/saferpay#12]
Hi, 

When I try to implement Saferpay I got this fatal error:
```
Fatal error: Class 'Saferpay' not found
```

I followed the readme but I can't make it work. I use a lot of other class and maybe it's a conflict bewteen classes and namespaces? Here is my composer.json file:

```
{
	"require": {
		"lichtner/fluentpdo": "dev-master",
		"respect/validation": "0.7.*@dev",
		"michelf/php-markdown": "1.3",
		"ircmaxell/password-compat": "dev-master",
		"phpmailer/phpmailer": "dev-master",
		"mobiledetect/mobiledetectlib": "dev-master",
		"frameworks/jquery": "dev-master",
		"components/modernizr": "dev-master",
		"donatj/phpuseragentparser": "*",
		"ifsnop/mysqldump-php": "dev-master",
		"Chumper/Zipper": "dev-master",
		"hashids/hashids": "1.0.0",
		"whatwedo/postfinance-e-payment": "dev-master",
		"kriswallsmith/buzz": "dev-master",
		"kriswallsmith/buzz": "~0.9",
		"ensepar/html2pdf": "dev-master",
		"psr/log": "1.0.*",
        "payment/httpclient": "1.0.*",
        "payment/httpclient-implementation": "~1.0"
	},
	"minimum-stability": "dev",
	"require-dev": {
        "payment/httpclient-buzz": "~1.1",
        "phpunit/phpunit": "3.7.*"
    },
	"autoload": {
        "files": [
			"app/core/Session.php",
			"app/classes/Paypal.php"
		],
		"psr-0": {
			"configuration": "app/classes",
			"Payment\\Saferpay\\": "src"
		}
	}
}
```
As I said, I use other payment classes for a small shop. Can you help me?

I tried to use it in a other project with only the files from this repo and it's working. I just copied the content of your files and everything was okay but when I mix it with my project it doesn't find the classe. And when I indicate the namespace, my other classes doesn't work. I use a MVC pattern.

**Comment by dominikzogg** [comment]
@beeInteractive Hello, whats the reason you do not use the composer.json of the repository?
https://github.com/payment/saferpay#with-buzz

**Comment by beeInteractive** [comment]
Is it not right to include the content of the composer.json from this repo into my composer.json? Can you explain me how to do it? I've always did this with my other projects:
Include the packages I need, the with the "use" keywords in my files and then "new class". But here, it doesn't seem to work..

**Comment by dominikzogg** [comment]
@beeInteractive for vendors like this library there is the require part, better use something like this

```{.json}
{
    "require": {
        "lichtner/fluentpdo": "dev-master",
        "respect/validation": "0.7.*@dev",
        "michelf/php-markdown": "1.3",
        "ircmaxell/password-compat": "dev-master",
        "phpmailer/phpmailer": "dev-master",
        "mobiledetect/mobiledetectlib": "dev-master",
        "frameworks/jquery": "dev-master",
        "components/modernizr": "dev-master",
        "donatj/phpuseragentparser": "*",
        "ifsnop/mysqldump-php": "dev-master",
        "Chumper/Zipper": "dev-master",
        "hashids/hashids": "1.0.0",
        "whatwedo/postfinance-e-payment": "dev-master",
        "kriswallsmith/buzz": "dev-master",
        "kriswallsmith/buzz": "~0.9",
        "ensepar/html2pdf": "dev-master",
        "psr/log": "1.0.*",
        "payment/saferpay": "~3.0",
        "payment/httpclient": "1.0.*",
        "payment/httpclient-implementation": "~1.0"
    },
    "minimum-stability": "dev",
    "require-dev": {
        "payment/httpclient-buzz": "~1.2",
        "phpunit/phpunit": "3.7.*"
    },
    "autoload": {
        "files": [
            "app/core/Session.php",
            "app/classes/Paypal.php"
        ],
        "psr-0": {
            "configuration": "app/classes"
        }
    }
}
```

**Comment by beeInteractive** [comment]
I followed your composer.json file and then, in my productController I try this:

```
<?php
namespace Payment\Saferpay;

use Payment\HttpClient\BuzzClient;
use Payment\Saferpay\Data\PayInitParameter;

$saferpay = new Saferpay;
$saferpay->setHttpClient(new BuzzClient());

var_dump($saferpay);

/**
* Products controller
*/
class ProductsController extends Controller
{
	function index() {
	}
}
```

The var_dump shows me some data from the Saferpay classe but I got this other error:
```
Fatal error: Class 'Payment\Saferpay\Controller' not found in /Users/Home/Sites/shop.dev/app/controllers/ProductsController.php
```

**Comment by dominikzogg** [comment]
@beeInteractiveYour own code should be in a diffrent namespace, not at Payment\Saferpay\ProductsController

**Comment by beeInteractive** [comment]
But I don't use any namespaces anywhere in my code.. And it always worked until now

**Comment by dominikzogg** [comment]
Well you do, in your example, remove the namespace row, in your code and
try it again.
Am 16.02.2015 08:40 schrieb "Yves Engetschwiler" <notifications@github.com>:

**Comment by beeInteractive** [comment]
When I remove the line "namespace Payment\Saferpay;" I got this other error: Fatal error: Class 'Saferpay' not found..

**Comment by dominikzogg** [comment]
@beeInteractive replace the namespace Payment\Saferpay; with use Payment\Saferpay;

**Comment by dominikzogg** [comment]
@beeInteractive please take a look within the phpdoc: http://php.net/manual/en/language.namespaces.php, you should understand it, to be able using modern libraries.

**Comment by beeInteractive** [comment]
Yes it worked! Thank you for the time!

**Comment by dominikzogg** [comment]
you're welcome
