### ISSUE TITLE
Builds of version >3.0.0 are failing

### ISSUE THREAD

**Issue by OlliM** [payment/saferpay#13]
Your build are failing since Version 3, maybe you can take a look into this?

**Comment by dominikzogg** [comment]
@OlliM Well probably saferpay remove some testdata, so i have to update mine, there is no real way to do a functional test as i like. So i am sure it still work.

**Comment by OlliM** [comment]
Thanks for your quick reply. :+1: 
I thought maybe it's related to the ibrows/PaymentSaferpayBundle not working...
